// <auto-generated />
using System;
using Library.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Library.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1942, 1, 25, 19, 56, 28, 576, DateTimeKind.Unspecified).AddTicks(2088),
                            Name = "София Владимирова"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1995, 1, 19, 17, 13, 34, 539, DateTimeKind.Unspecified).AddTicks(3378),
                            Name = "Алевтина Соколова"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1967, 5, 21, 12, 8, 4, 999, DateTimeKind.Unspecified).AddTicks(4416),
                            Name = "Константин Белозеров"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1939, 4, 15, 2, 29, 45, 461, DateTimeKind.Unspecified).AddTicks(2644),
                            Name = "Даниил Воробьев"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1931, 9, 27, 1, 9, 20, 750, DateTimeKind.Unspecified).AddTicks(3164),
                            Name = "Валентина Иванова"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2006, 10, 29, 15, 22, 32, 330, DateTimeKind.Unspecified).AddTicks(9727),
                            Name = "Алексей Мишин"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1935, 1, 18, 13, 14, 28, 393, DateTimeKind.Unspecified).AddTicks(5284),
                            Name = "Лидия Агафонова"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1938, 10, 23, 20, 33, 26, 574, DateTimeKind.Unspecified).AddTicks(6400),
                            Name = "Ангелина Савина"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1999, 7, 8, 18, 31, 33, 286, DateTimeKind.Unspecified).AddTicks(9656),
                            Name = "Алина Игнатьева"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1943, 3, 22, 19, 51, 27, 575, DateTimeKind.Unspecified).AddTicks(7492),
                            Name = "Антонина Афанасьева"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1991, 8, 4, 12, 56, 25, 491, DateTimeKind.Unspecified).AddTicks(9785),
                            Name = "Светлана Трофимова"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1976, 4, 9, 4, 38, 11, 340, DateTimeKind.Unspecified).AddTicks(8952),
                            Name = "Анастасия Королева"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1994, 8, 11, 7, 51, 51, 158, DateTimeKind.Unspecified).AddTicks(5422),
                            Name = "Денис Зимин"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1930, 3, 12, 3, 8, 59, 88, DateTimeKind.Unspecified).AddTicks(6924),
                            Name = "Иван Брагин"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1998, 12, 3, 5, 26, 19, 527, DateTimeKind.Unspecified).AddTicks(5645),
                            Name = "Матвей Павлов"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2002, 8, 26, 11, 24, 20, 630, DateTimeKind.Unspecified).AddTicks(3719),
                            Name = "Аркадий Горбачев"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1997, 8, 24, 22, 10, 3, 843, DateTimeKind.Unspecified).AddTicks(9422),
                            Name = "Альберт Молчанов"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1978, 2, 8, 10, 1, 38, 325, DateTimeKind.Unspecified).AddTicks(1592),
                            Name = "Юлия Бурова"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1985, 4, 7, 12, 32, 58, 27, DateTimeKind.Unspecified).AddTicks(713),
                            Name = "Антонина Кузнецова"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1955, 9, 16, 2, 24, 52, 437, DateTimeKind.Unspecified).AddTicks(4666),
                            Name = "Клавдия Журавлева"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2003, 7, 28, 10, 32, 15, 698, DateTimeKind.Unspecified).AddTicks(1350),
                            Name = "Виталий Молчанов"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1990, 1, 14, 3, 31, 52, 471, DateTimeKind.Unspecified).AddTicks(4672),
                            Name = "Григорий Бирюков"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1992, 12, 2, 19, 29, 27, 691, DateTimeKind.Unspecified).AddTicks(8998),
                            Name = "Константин Фокин"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1941, 11, 14, 3, 37, 57, 108, DateTimeKind.Unspecified).AddTicks(332),
                            Name = "Виталий Родионов"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1951, 1, 8, 22, 33, 10, 769, DateTimeKind.Unspecified).AddTicks(292),
                            Name = "Григорий Степанов"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1992, 10, 4, 20, 2, 20, 43, DateTimeKind.Unspecified).AddTicks(211),
                            Name = "Анатолий Овчинников"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1942, 11, 21, 1, 10, 52, 329, DateTimeKind.Unspecified).AddTicks(3412),
                            Name = "Вера Петухова"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1963, 9, 9, 5, 36, 23, 643, DateTimeKind.Unspecified).AddTicks(4994),
                            Name = "Ирина Гаврилова"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2002, 1, 9, 5, 2, 53, 263, DateTimeKind.Unspecified).AddTicks(1738),
                            Name = "Герман Евдокимов"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1959, 7, 24, 13, 57, 43, 567, DateTimeKind.Unspecified).AddTicks(1016),
                            Name = "Игорь Моисеев"
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(1987, 12, 27, 10, 17, 53, 730, DateTimeKind.Unspecified).AddTicks(7319),
                            Name = "Егор Сазонов"
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(1963, 8, 22, 21, 13, 59, 278, DateTimeKind.Unspecified).AddTicks(2836),
                            Name = "Михаил Никитин"
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(1999, 7, 29, 14, 35, 31, 779, DateTimeKind.Unspecified).AddTicks(1006),
                            Name = "Антонида Кузнецова"
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(1976, 2, 15, 23, 58, 27, 111, DateTimeKind.Unspecified).AddTicks(3064),
                            Name = "Иван Осипов"
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(1998, 11, 25, 14, 32, 34, 396, DateTimeKind.Unspecified).AddTicks(1158),
                            Name = "Кира Трофимова"
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(1951, 3, 12, 12, 50, 41, 919, DateTimeKind.Unspecified).AddTicks(7120),
                            Name = "Альберт Прохоров"
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(1948, 5, 25, 9, 45, 49, 415, DateTimeKind.Unspecified).AddTicks(2784),
                            Name = "Григорий Нестеров"
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(1953, 1, 15, 16, 33, 50, 813, DateTimeKind.Unspecified).AddTicks(3000),
                            Name = "Виктория Родионова"
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(1938, 11, 4, 6, 23, 43, 248, DateTimeKind.Unspecified).AddTicks(4968),
                            Name = "Кира Воронова"
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(1943, 4, 28, 16, 19, 57, 982, DateTimeKind.Unspecified).AddTicks(9748),
                            Name = "Виктор Степанов"
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(1979, 8, 11, 13, 14, 20, 816, DateTimeKind.Unspecified).AddTicks(3414),
                            Name = "Михаил Козлов"
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(1930, 12, 2, 8, 7, 2, 571, DateTimeKind.Unspecified).AddTicks(8648),
                            Name = "Вера Макарова"
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(1941, 2, 24, 20, 29, 28, 906, DateTimeKind.Unspecified).AddTicks(436),
                            Name = "Василий Дорофеев"
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(1992, 11, 30, 1, 9, 42, 41, DateTimeKind.Unspecified).AddTicks(8929),
                            Name = "Евгений Третьяков"
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(1959, 4, 25, 21, 43, 30, 241, DateTimeKind.Unspecified).AddTicks(1186),
                            Name = "Анжелика Морозова"
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(1974, 9, 13, 3, 42, 34, 91, DateTimeKind.Unspecified).AddTicks(5640),
                            Name = "Денис Самойлов"
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(1937, 12, 21, 11, 23, 55, 894, DateTimeKind.Unspecified).AddTicks(5576),
                            Name = "Вера Белоусова"
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(1966, 4, 15, 11, 11, 28, 172, DateTimeKind.Unspecified).AddTicks(4410),
                            Name = "Герман Королев"
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(1977, 6, 7, 0, 3, 37, 599, DateTimeKind.Unspecified).AddTicks(3026),
                            Name = "Макар Селиверстов"
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(1937, 8, 17, 22, 3, 1, 337, DateTimeKind.Unspecified).AddTicks(404),
                            Name = "Владислав Степанов"
                        },
                        new
                        {
                            Id = 51,
                            DateOfBirth = new DateTime(1975, 3, 31, 19, 12, 44, 93, DateTimeKind.Unspecified).AddTicks(7218),
                            Name = "Максим Ермаков"
                        },
                        new
                        {
                            Id = 52,
                            DateOfBirth = new DateTime(1982, 1, 28, 3, 16, 36, 653, DateTimeKind.Unspecified).AddTicks(3000),
                            Name = "Илья Ермаков"
                        },
                        new
                        {
                            Id = 53,
                            DateOfBirth = new DateTime(2004, 8, 25, 11, 42, 39, 400, DateTimeKind.Unspecified).AddTicks(1117),
                            Name = "Виталий Смирнов"
                        },
                        new
                        {
                            Id = 54,
                            DateOfBirth = new DateTime(1955, 5, 1, 21, 51, 11, 804, DateTimeKind.Unspecified).AddTicks(6986),
                            Name = "Игнатий Крюков"
                        },
                        new
                        {
                            Id = 55,
                            DateOfBirth = new DateTime(1990, 10, 19, 7, 41, 46, 192, DateTimeKind.Unspecified).AddTicks(3603),
                            Name = "Лариса Ермакова"
                        },
                        new
                        {
                            Id = 56,
                            DateOfBirth = new DateTime(1947, 11, 21, 19, 32, 32, 851, DateTimeKind.Unspecified).AddTicks(8692),
                            Name = "Василий Беспалов"
                        },
                        new
                        {
                            Id = 57,
                            DateOfBirth = new DateTime(1975, 6, 29, 12, 15, 0, 20, DateTimeKind.Unspecified).AddTicks(8478),
                            Name = "Михаил Тихонов"
                        },
                        new
                        {
                            Id = 58,
                            DateOfBirth = new DateTime(1965, 8, 2, 20, 51, 19, 638, DateTimeKind.Unspecified).AddTicks(2224),
                            Name = "Алина Яковлева"
                        },
                        new
                        {
                            Id = 59,
                            DateOfBirth = new DateTime(1979, 6, 1, 14, 12, 49, 68, DateTimeKind.Unspecified).AddTicks(3663),
                            Name = "Артём Матвеев"
                        },
                        new
                        {
                            Id = 60,
                            DateOfBirth = new DateTime(1994, 10, 20, 7, 34, 10, 87, DateTimeKind.Unspecified).AddTicks(2500),
                            Name = "Жанна Антонова"
                        },
                        new
                        {
                            Id = 61,
                            DateOfBirth = new DateTime(1946, 9, 5, 22, 18, 21, 9, DateTimeKind.Unspecified).AddTicks(3004),
                            Name = "Татьяна Зиновьева"
                        },
                        new
                        {
                            Id = 62,
                            DateOfBirth = new DateTime(1939, 12, 13, 18, 55, 45, 60, DateTimeKind.Unspecified).AddTicks(1820),
                            Name = "Артём Осипов"
                        },
                        new
                        {
                            Id = 63,
                            DateOfBirth = new DateTime(1975, 8, 20, 18, 12, 12, 177, DateTimeKind.Unspecified).AddTicks(2300),
                            Name = "Вера Архипова"
                        },
                        new
                        {
                            Id = 64,
                            DateOfBirth = new DateTime(2002, 2, 24, 4, 56, 6, 934, DateTimeKind.Unspecified).AddTicks(9813),
                            Name = "Татьяна Гуляева"
                        },
                        new
                        {
                            Id = 65,
                            DateOfBirth = new DateTime(1980, 9, 18, 11, 44, 57, 137, DateTimeKind.Unspecified).AddTicks(2042),
                            Name = "Регина Веселова"
                        },
                        new
                        {
                            Id = 66,
                            DateOfBirth = new DateTime(2005, 7, 28, 7, 58, 47, 143, DateTimeKind.Unspecified).AddTicks(8941),
                            Name = "Борис Симонов"
                        },
                        new
                        {
                            Id = 67,
                            DateOfBirth = new DateTime(2001, 1, 2, 16, 57, 7, 312, DateTimeKind.Unspecified).AddTicks(9479),
                            Name = "Дмитрий Соколов"
                        },
                        new
                        {
                            Id = 68,
                            DateOfBirth = new DateTime(1975, 6, 1, 9, 22, 55, 121, DateTimeKind.Unspecified).AddTicks(5452),
                            Name = "Геннадий Артемьев"
                        },
                        new
                        {
                            Id = 69,
                            DateOfBirth = new DateTime(1998, 2, 23, 8, 47, 30, 882, DateTimeKind.Unspecified).AddTicks(7744),
                            Name = "Григорий Быков"
                        },
                        new
                        {
                            Id = 70,
                            DateOfBirth = new DateTime(1933, 7, 11, 16, 7, 7, 962, DateTimeKind.Unspecified).AddTicks(8504),
                            Name = "Арсений Марков"
                        },
                        new
                        {
                            Id = 71,
                            DateOfBirth = new DateTime(1990, 4, 25, 11, 10, 37, 240, DateTimeKind.Unspecified).AddTicks(278),
                            Name = "Клавдия Исакова"
                        },
                        new
                        {
                            Id = 72,
                            DateOfBirth = new DateTime(2002, 6, 6, 17, 36, 57, 736, DateTimeKind.Unspecified).AddTicks(5151),
                            Name = "Нина Дементьева"
                        },
                        new
                        {
                            Id = 73,
                            DateOfBirth = new DateTime(2002, 6, 15, 3, 39, 43, 119, DateTimeKind.Unspecified).AddTicks(2868),
                            Name = "Валентин Горшков"
                        },
                        new
                        {
                            Id = 74,
                            DateOfBirth = new DateTime(1961, 10, 5, 2, 27, 36, 832, DateTimeKind.Unspecified).AddTicks(5918),
                            Name = "Юрий Фокин"
                        },
                        new
                        {
                            Id = 75,
                            DateOfBirth = new DateTime(1932, 11, 26, 5, 18, 17, 903, DateTimeKind.Unspecified).AddTicks(5824),
                            Name = "Матвей Кириллов"
                        },
                        new
                        {
                            Id = 76,
                            DateOfBirth = new DateTime(1959, 3, 12, 13, 30, 59, 331, DateTimeKind.Unspecified).AddTicks(1028),
                            Name = "Борис Хохлов"
                        },
                        new
                        {
                            Id = 77,
                            DateOfBirth = new DateTime(1981, 1, 18, 17, 13, 20, 474, DateTimeKind.Unspecified).AddTicks(5578),
                            Name = "Алла Воробьева"
                        },
                        new
                        {
                            Id = 78,
                            DateOfBirth = new DateTime(1950, 9, 10, 6, 28, 17, 381, DateTimeKind.Unspecified).AddTicks(1482),
                            Name = "Маргарита Жданова"
                        },
                        new
                        {
                            Id = 79,
                            DateOfBirth = new DateTime(1958, 11, 6, 9, 48, 1, 363, DateTimeKind.Unspecified).AddTicks(1044),
                            Name = "Дарья Константинова"
                        },
                        new
                        {
                            Id = 80,
                            DateOfBirth = new DateTime(1976, 12, 8, 2, 36, 12, 864, DateTimeKind.Unspecified).AddTicks(3536),
                            Name = "Кира Исакова"
                        },
                        new
                        {
                            Id = 81,
                            DateOfBirth = new DateTime(2002, 10, 30, 3, 36, 37, 53, DateTimeKind.Unspecified).AddTicks(9511),
                            Name = "Татьяна Пахомова"
                        },
                        new
                        {
                            Id = 82,
                            DateOfBirth = new DateTime(1980, 3, 26, 22, 39, 2, 65, DateTimeKind.Unspecified).AddTicks(519),
                            Name = "Маргарита Цветкова"
                        },
                        new
                        {
                            Id = 83,
                            DateOfBirth = new DateTime(1946, 7, 6, 23, 54, 36, 753, DateTimeKind.Unspecified).AddTicks(7548),
                            Name = "Сергей Лихачев"
                        },
                        new
                        {
                            Id = 84,
                            DateOfBirth = new DateTime(1982, 4, 5, 20, 8, 13, 862, DateTimeKind.Unspecified).AddTicks(2649),
                            Name = "Дарья Мишина"
                        },
                        new
                        {
                            Id = 85,
                            DateOfBirth = new DateTime(1966, 6, 2, 13, 16, 19, 319, DateTimeKind.Unspecified).AddTicks(2594),
                            Name = "Олег Костин"
                        },
                        new
                        {
                            Id = 86,
                            DateOfBirth = new DateTime(1952, 9, 10, 8, 24, 13, 494, DateTimeKind.Unspecified).AddTicks(8194),
                            Name = "Екатерина Белякова"
                        },
                        new
                        {
                            Id = 87,
                            DateOfBirth = new DateTime(1946, 1, 22, 12, 54, 39, 428, DateTimeKind.Unspecified).AddTicks(9852),
                            Name = "Оксана Лобанова"
                        },
                        new
                        {
                            Id = 88,
                            DateOfBirth = new DateTime(1957, 7, 28, 1, 59, 7, 841, DateTimeKind.Unspecified).AddTicks(2570),
                            Name = "Вячеслав Носов"
                        },
                        new
                        {
                            Id = 89,
                            DateOfBirth = new DateTime(1992, 8, 3, 4, 39, 58, 791, DateTimeKind.Unspecified).AddTicks(5296),
                            Name = "Валерий Медведев"
                        },
                        new
                        {
                            Id = 90,
                            DateOfBirth = new DateTime(1935, 8, 5, 10, 54, 40, 564, DateTimeKind.Unspecified).AddTicks(256),
                            Name = "Евгений Рогов"
                        },
                        new
                        {
                            Id = 91,
                            DateOfBirth = new DateTime(1957, 1, 10, 22, 43, 50, 794, DateTimeKind.Unspecified).AddTicks(6066),
                            Name = "Надежда Одинцова"
                        },
                        new
                        {
                            Id = 92,
                            DateOfBirth = new DateTime(1998, 1, 22, 17, 20, 54, 176, DateTimeKind.Unspecified).AddTicks(7441),
                            Name = "Ольга Захарова"
                        },
                        new
                        {
                            Id = 93,
                            DateOfBirth = new DateTime(1931, 1, 18, 4, 23, 0, 323, DateTimeKind.Unspecified).AddTicks(7484),
                            Name = "Зоя Воронцова"
                        },
                        new
                        {
                            Id = 94,
                            DateOfBirth = new DateTime(1984, 10, 16, 21, 50, 55, 557, DateTimeKind.Unspecified).AddTicks(4724),
                            Name = "София Харитонова"
                        },
                        new
                        {
                            Id = 95,
                            DateOfBirth = new DateTime(2001, 5, 13, 22, 6, 55, 462, DateTimeKind.Unspecified).AddTicks(5056),
                            Name = "Алексей Блинов"
                        },
                        new
                        {
                            Id = 96,
                            DateOfBirth = new DateTime(1999, 2, 25, 7, 37, 58, 133, DateTimeKind.Unspecified).AddTicks(3679),
                            Name = "Денис Борисов"
                        },
                        new
                        {
                            Id = 97,
                            DateOfBirth = new DateTime(1983, 6, 10, 1, 53, 52, 86, DateTimeKind.Unspecified).AddTicks(1401),
                            Name = "Владимир Родионов"
                        },
                        new
                        {
                            Id = 98,
                            DateOfBirth = new DateTime(1965, 11, 10, 19, 3, 35, 838, DateTimeKind.Unspecified).AddTicks(2364),
                            Name = "Илья Константинов"
                        },
                        new
                        {
                            Id = 99,
                            DateOfBirth = new DateTime(1931, 2, 17, 9, 54, 0, 325, DateTimeKind.Unspecified).AddTicks(8728),
                            Name = "Матвей Исаев"
                        },
                        new
                        {
                            Id = 100,
                            DateOfBirth = new DateTime(1939, 3, 4, 17, 49, 28, 864, DateTimeKind.Unspecified).AddTicks(8092),
                            Name = "Таисия Самсонова"
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 22,
                            PublishedYear = 2014,
                            Title = "Предпосылки плановых технологий всего важную."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 71,
                            PublishedYear = 2019,
                            Title = "Обучения информационно-пропогандистское особенности."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            PublishedYear = 1989,
                            Title = "Соответствующих позиции."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 99,
                            PublishedYear = 1984,
                            Title = "Обеспечение реализация важную намеченных не."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 57,
                            PublishedYear = 1998,
                            Title = "Очевидна модернизации."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 44,
                            PublishedYear = 2017,
                            Title = "Обуславливает сфера повышение следует."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 48,
                            PublishedYear = 2006,
                            Title = "Поставленных обеспечение активности также модернизации."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 39,
                            PublishedYear = 2023,
                            Title = "Развития отношении не информационно-пропогандистское."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 27,
                            PublishedYear = 2000,
                            Title = "Инновационный понимание задания."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 90,
                            PublishedYear = 2021,
                            Title = "Эксперимент разработке."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 41,
                            PublishedYear = 2022,
                            Title = "Соответствующей равным степени проблем."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 19,
                            PublishedYear = 1989,
                            Title = "Другой место а."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 54,
                            PublishedYear = 2005,
                            Title = "Активом нами."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 28,
                            PublishedYear = 1997,
                            Title = "Форм массового."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 59,
                            PublishedYear = 1984,
                            Title = "Принципов что постоянный проверки зависит."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 77,
                            PublishedYear = 1985,
                            Title = "Формированию экономической прогресса понимание."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 88,
                            PublishedYear = 1977,
                            Title = "Общественной экономической."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            PublishedYear = 2006,
                            Title = "Очевидна повышение."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 14,
                            PublishedYear = 1989,
                            Title = "Участниками работы опыт."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 47,
                            PublishedYear = 1991,
                            Title = "Демократической повышению собой значимость."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 36,
                            PublishedYear = 2015,
                            Title = "Гражданского нами реализация мира системы."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 96,
                            PublishedYear = 1996,
                            Title = "Показывает представляет отметить."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 60,
                            PublishedYear = 2019,
                            Title = "Профессионального значимость обучения."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 100,
                            PublishedYear = 2018,
                            Title = "Задания информационно-пропогандистское дальнейших."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 97,
                            PublishedYear = 2006,
                            Title = "Нашей повышение актуальность активности порядка."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 19,
                            PublishedYear = 2007,
                            Title = "Стороны подготовке."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 13,
                            PublishedYear = 1976,
                            Title = "Задач соответствующей административных национальный важные."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 35,
                            PublishedYear = 2008,
                            Title = "Качественно опыт."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 88,
                            PublishedYear = 1995,
                            Title = "Выбранный в."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 82,
                            PublishedYear = 1978,
                            Title = "Поэтапного модели."
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 50,
                            PublishedYear = 1989,
                            Title = "Общественной повышению важные высшего практика."
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 42,
                            PublishedYear = 2008,
                            Title = "Степени интересный."
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 65,
                            PublishedYear = 1981,
                            Title = "Зависит сущности важные же."
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 48,
                            PublishedYear = 1991,
                            Title = "Влечёт развития."
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 77,
                            PublishedYear = 2009,
                            Title = "Уточнения проверки широким."
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 87,
                            PublishedYear = 2024,
                            Title = "Степени насущным широким поставленных стороны."
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 76,
                            PublishedYear = 2019,
                            Title = "Опыт собой модернизации оценить."
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 46,
                            PublishedYear = 2002,
                            Title = "Общественной образом а за."
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 59,
                            PublishedYear = 1982,
                            Title = "Работы сложившаяся рост."
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 50,
                            PublishedYear = 2006,
                            Title = "Работы внедрения повседневной соответствующих внедрения."
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 7,
                            PublishedYear = 2023,
                            Title = "Принимаемых потребностям."
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 21,
                            PublishedYear = 1987,
                            Title = "Нами задача нас."
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 17,
                            PublishedYear = 1976,
                            Title = "Реализация предпосылки отметить интересный."
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 84,
                            PublishedYear = 2014,
                            Title = "Обуславливает позиции путь."
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 43,
                            PublishedYear = 1999,
                            Title = "Образом богатый степени не кадровой."
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 10,
                            PublishedYear = 1975,
                            Title = "Качества прежде соображения специалистов."
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 3,
                            PublishedYear = 2008,
                            Title = "Высшего высшего."
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 55,
                            PublishedYear = 1983,
                            Title = "Курс сущности и значительной."
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 76,
                            PublishedYear = 2003,
                            Title = "Системы формировании формировании насущным."
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 80,
                            PublishedYear = 1999,
                            Title = "Проверки информационно-пропогандистское."
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 47,
                            PublishedYear = 1984,
                            Title = "Инновационный современного."
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 45,
                            PublishedYear = 2009,
                            Title = "Путь обеспечение эксперимент внедрения забывать."
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 84,
                            PublishedYear = 1997,
                            Title = "Занимаемых материально-технической развития."
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 32,
                            PublishedYear = 1984,
                            Title = "Показывает различных существующий профессионального."
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 92,
                            PublishedYear = 2002,
                            Title = "Нашей внедрения формировании."
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 41,
                            PublishedYear = 2001,
                            Title = "Модели идейные сомнений следует."
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 58,
                            PublishedYear = 1997,
                            Title = "Повседневной общества."
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 34,
                            PublishedYear = 2002,
                            Title = "Принимаемых плановых активизации интересный."
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 41,
                            PublishedYear = 2013,
                            Title = "Обеспечение сфера."
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 30,
                            PublishedYear = 1988,
                            Title = "Высшего активности за."
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 13,
                            PublishedYear = 1989,
                            Title = "Богатый прежде кадров."
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 15,
                            PublishedYear = 2013,
                            Title = "Не позволяет."
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 17,
                            PublishedYear = 2021,
                            Title = "Гражданского дальнейших для кругу."
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 74,
                            PublishedYear = 1999,
                            Title = "Кадров другой представляет практика направлений."
                        },
                        new
                        {
                            Id = 65,
                            AuthorId = 46,
                            PublishedYear = 1992,
                            Title = "Социально-ориентированный общества."
                        },
                        new
                        {
                            Id = 66,
                            AuthorId = 52,
                            PublishedYear = 2020,
                            Title = "Оценить изменений."
                        },
                        new
                        {
                            Id = 67,
                            AuthorId = 12,
                            PublishedYear = 1979,
                            Title = "Направлений участниками нашей технологий стороны."
                        },
                        new
                        {
                            Id = 68,
                            AuthorId = 85,
                            PublishedYear = 2023,
                            Title = "Сознания следует гражданского количественный всего."
                        },
                        new
                        {
                            Id = 69,
                            AuthorId = 29,
                            PublishedYear = 2003,
                            Title = "От же разработке."
                        },
                        new
                        {
                            Id = 70,
                            AuthorId = 78,
                            PublishedYear = 1980,
                            Title = "Шагов богатый модели целесообразности."
                        },
                        new
                        {
                            Id = 71,
                            AuthorId = 25,
                            PublishedYear = 1988,
                            Title = "Дальнейшее требует активом прежде намеченных."
                        },
                        new
                        {
                            Id = 72,
                            AuthorId = 40,
                            PublishedYear = 2000,
                            Title = "Настолько место разнообразный."
                        },
                        new
                        {
                            Id = 73,
                            AuthorId = 61,
                            PublishedYear = 1993,
                            Title = "Широким целесообразности позиции направлений."
                        },
                        new
                        {
                            Id = 74,
                            AuthorId = 96,
                            PublishedYear = 1994,
                            Title = "Активности внедрения нашей воздействия профессионального."
                        },
                        new
                        {
                            Id = 75,
                            AuthorId = 6,
                            PublishedYear = 2008,
                            Title = "Поставленных технологий активом."
                        },
                        new
                        {
                            Id = 76,
                            AuthorId = 61,
                            PublishedYear = 2009,
                            Title = "Сфера вызывает проблем с."
                        },
                        new
                        {
                            Id = 77,
                            AuthorId = 100,
                            PublishedYear = 2024,
                            Title = "Гражданского структура административных форм требует."
                        },
                        new
                        {
                            Id = 78,
                            AuthorId = 17,
                            PublishedYear = 2011,
                            Title = "Сложившаяся предложений."
                        },
                        new
                        {
                            Id = 79,
                            AuthorId = 29,
                            PublishedYear = 2019,
                            Title = "Выполнять социально-ориентированный проблем позиции профессионального."
                        },
                        new
                        {
                            Id = 80,
                            AuthorId = 16,
                            PublishedYear = 1990,
                            Title = "Сознания обуславливает."
                        },
                        new
                        {
                            Id = 81,
                            AuthorId = 61,
                            PublishedYear = 1979,
                            Title = "Важную высокотехнологичная сфера."
                        },
                        new
                        {
                            Id = 82,
                            AuthorId = 38,
                            PublishedYear = 2013,
                            Title = "А шагов управление."
                        },
                        new
                        {
                            Id = 83,
                            AuthorId = 26,
                            PublishedYear = 1977,
                            Title = "Современного практика."
                        },
                        new
                        {
                            Id = 84,
                            AuthorId = 45,
                            PublishedYear = 2022,
                            Title = "Консультация системы задач важную последовательного."
                        },
                        new
                        {
                            Id = 85,
                            AuthorId = 85,
                            PublishedYear = 2009,
                            Title = "Воздействия занимаемых."
                        },
                        new
                        {
                            Id = 86,
                            AuthorId = 96,
                            PublishedYear = 1997,
                            Title = "Общества модернизации создание."
                        },
                        new
                        {
                            Id = 87,
                            AuthorId = 20,
                            PublishedYear = 2023,
                            Title = "И существующий активизации формировании за."
                        },
                        new
                        {
                            Id = 88,
                            AuthorId = 83,
                            PublishedYear = 2008,
                            Title = "Количественный обеспечивает требует плановых."
                        },
                        new
                        {
                            Id = 89,
                            AuthorId = 43,
                            PublishedYear = 2022,
                            Title = "Другой участниками широкому концепция отношении."
                        },
                        new
                        {
                            Id = 90,
                            AuthorId = 6,
                            PublishedYear = 1985,
                            Title = "Повышение деятельности равным демократической постоянное."
                        },
                        new
                        {
                            Id = 91,
                            AuthorId = 95,
                            PublishedYear = 2022,
                            Title = "Изменений прогресса влечёт."
                        },
                        new
                        {
                            Id = 92,
                            AuthorId = 46,
                            PublishedYear = 2006,
                            Title = "Соответствующих активности актуальность."
                        },
                        new
                        {
                            Id = 93,
                            AuthorId = 99,
                            PublishedYear = 1990,
                            Title = "Работы задача."
                        },
                        new
                        {
                            Id = 94,
                            AuthorId = 81,
                            PublishedYear = 2005,
                            Title = "Нами кругу."
                        },
                        new
                        {
                            Id = 95,
                            AuthorId = 49,
                            PublishedYear = 2022,
                            Title = "Организационной степени создание."
                        },
                        new
                        {
                            Id = 96,
                            AuthorId = 67,
                            PublishedYear = 2022,
                            Title = "Организационной требует предпосылки соображения играет."
                        },
                        new
                        {
                            Id = 97,
                            AuthorId = 25,
                            PublishedYear = 1976,
                            Title = "Качественно создание анализа требует гражданского."
                        },
                        new
                        {
                            Id = 98,
                            AuthorId = 35,
                            PublishedYear = 2018,
                            Title = "Поэтапного информационно-пропогандистское."
                        },
                        new
                        {
                            Id = 99,
                            AuthorId = 66,
                            PublishedYear = 1999,
                            Title = "Различных дальнейшее интересный."
                        },
                        new
                        {
                            Id = 100,
                            AuthorId = 78,
                            PublishedYear = 1979,
                            Title = "Формированию занимаемых инновационный качества."
                        });
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.HasOne("Library.Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Library.Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
